#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>
#include "mmm.h"

/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init(int size)
{
	A = (double**)malloc(sizeof(double*)*size);
	for(int i=0; i<size; i++) {
		A[i] = (double*)malloc(sizeof(double)*size);
	}

	B = (double**)malloc(sizeof(double*)*size);
	for(int i=0; i<size; i++) {
		B[i] = (double*)malloc(sizeof(double)*size);
	}

	C = (double**)malloc(sizeof(double*)*size);
	for(int i=0; i<size; i++) {
		C[i] = (double*)malloc(sizeof(double)*size);
	}

	D = (double**)malloc(sizeof(double*)*size);
	for(int i=0; i<size; i++) {
		D[i] = (double*)malloc(sizeof(double)*size);
	}

	for(int i=0; i<size; i++) {
		for(int j=0; j<size; j++) {
			A[i][j] = rand() % 100;
		}
	}
	
	for(int i=0; i<size; i++) {
		for(int j=0; j<size; j++) {
			B[i][j] = rand() % 100;
		}
	}

	for(int i=0; i<size; i++) {
		for(int j=0; j<size; j++) {
			C[i][j] = 0;
		}
	}

	for(int i=0; i<size; i++) {
		for(int j=0; j<size; j++) {
			D[i][j] = 0;
		}
	}
}

/**
 * Reset a given matrix to zeroes
 */
void mmm_reset(double **matrix)
{
	for(int i=0; i<currSize; i++) {
		for(int j=0; j<currSize; j++) {
			matrix[i][j] = 0;
		}
	}
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup()
{
	free(A);
	free(B);
	free(C);
	free(D);
}

/**
 * Sequential MMM
 */
void mmm_seq()
{
	for(int i=0; i<currSize; i++) {
		for(int j=0; j<currSize; j++) {
			for(int k=0; k<currSize; k++) {
				C[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args)
{
	thread_args *params = (thread_args *)args;
	for(int i=params->start; i<params->end; i++){
		for(int j=0; j<currSize; j++){
			for(int k=0; k<currSize; k++){
				D[i][j] += A[i][k] * B[k][j];
			}
		}
	}
	return NULL;
}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 */
double mmm_verify()
{
	double biggestError = 0;
	for(int i=0; i<currSize; i++) {
		for(int j=0; j<currSize; j++) {
			if(C[i][j] != D[i][j]) {
				int temp = C[i][j] - D[i][j];
				if(temp > biggestError){
					biggestError = temp;
				}
			}
		}
	}
	return biggestError;
}
